### ISSUE TITLE
[Project App] Scrolling of project titles in project list

### ISSUE THREAD

**Issue by tbause** [SMPTE/smpte-skn-platform#30]
I’d suggest no scrolling on the project name and advise people to keep it short (and I also agree removing the TC from project titles in favor of assigned TC field).

**Comment by tbause** [comment]
We have a few options here, leave as is, cut off the project title, change the font or make the box height. I think cutting off the title or changing the font is not a good option. Changing the box height will change the density of the list. Lets see how it works for folks and may be change the box height later. This may be also an opportunity to not use very long project titles. 😉 Generally project owners are responsible for the project data and they change the title if the want after the migrations is done.

**Comment by sgusciora-smpte** [comment]
The latest update will switch the title field to cut off the project title if it is too long. The decision was made because when making the field clickable, it must be changed from a standard text field to a button field in order to have the pointer cursor to show the title can be clicked. Using the button field does not have the same text-wrapping properties as the text field.

I will leave this open for now in case there is any further discussion.
